quarkus.http.cors=true
quarkus.http.cors.origins=https://app.poa.ifrs.edu.br, http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE
quarkus.jackson.date-format=dd/MM/yyyy
smallrye.jwt.sign.key.location=privateKey.pem
smallrye.jwt.verify.key.location=publicKey.pem
mp.jwt.verify.issuer=sage-app
mp.jwt.verify.clock.skew=60
quarkus.swagger-ui.enable=true
quarkus.swagger-ui.always-include=true
quarkus.smallrye-jwt.enabled=true